package com.xuxincheng.bean;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.uuid
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sex
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.gradeId
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    private String gradeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.meetPhone
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    private String meetphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.status
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.createTime
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    private Integer createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.isTrainExp
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    private Integer istrainexp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.creatorId
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    private String creatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.serial
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    private String serial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.address
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.schoolId
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    private String schoolid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.phone
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.birthday
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    private Integer birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.ename
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.manageId
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    private String manageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.patriarchName
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    private String patriarchname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.studystatus
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    private String studystatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.isRelation
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    private Integer isrelation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.patriarch
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    private String patriarch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.updateTime
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    private Integer updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.namePinyin
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    private String namepinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.remark
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.uuid
     *
     * @return the value of student.uuid
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.uuid
     *
     * @param uuid the value for student.uuid
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sex
     *
     * @return the value of student.sex
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sex
     *
     * @param sex the value for student.sex
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.gradeId
     *
     * @return the value of student.gradeId
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public String getGradeid() {
        return gradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.gradeId
     *
     * @param gradeid the value for student.gradeId
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public void setGradeid(String gradeid) {
        this.gradeid = gradeid == null ? null : gradeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.meetPhone
     *
     * @return the value of student.meetPhone
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public String getMeetphone() {
        return meetphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.meetPhone
     *
     * @param meetphone the value for student.meetPhone
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public void setMeetphone(String meetphone) {
        this.meetphone = meetphone == null ? null : meetphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.status
     *
     * @return the value of student.status
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.status
     *
     * @param status the value for student.status
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.createTime
     *
     * @return the value of student.createTime
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public Integer getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.createTime
     *
     * @param createtime the value for student.createTime
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public void setCreatetime(Integer createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.isTrainExp
     *
     * @return the value of student.isTrainExp
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public Integer getIstrainexp() {
        return istrainexp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.isTrainExp
     *
     * @param istrainexp the value for student.isTrainExp
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public void setIstrainexp(Integer istrainexp) {
        this.istrainexp = istrainexp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.creatorId
     *
     * @return the value of student.creatorId
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public String getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.creatorId
     *
     * @param creatorid the value for student.creatorId
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public void setCreatorid(String creatorid) {
        this.creatorid = creatorid == null ? null : creatorid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.serial
     *
     * @return the value of student.serial
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public String getSerial() {
        return serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.serial
     *
     * @param serial the value for student.serial
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public void setSerial(String serial) {
        this.serial = serial == null ? null : serial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.address
     *
     * @return the value of student.address
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.address
     *
     * @param address the value for student.address
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.schoolId
     *
     * @return the value of student.schoolId
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public String getSchoolid() {
        return schoolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.schoolId
     *
     * @param schoolid the value for student.schoolId
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public void setSchoolid(String schoolid) {
        this.schoolid = schoolid == null ? null : schoolid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.phone
     *
     * @return the value of student.phone
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.phone
     *
     * @param phone the value for student.phone
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.birthday
     *
     * @return the value of student.birthday
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public Integer getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.birthday
     *
     * @param birthday the value for student.birthday
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public void setBirthday(Integer birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.ename
     *
     * @return the value of student.ename
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.ename
     *
     * @param ename the value for student.ename
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.manageId
     *
     * @return the value of student.manageId
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public String getManageid() {
        return manageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.manageId
     *
     * @param manageid the value for student.manageId
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public void setManageid(String manageid) {
        this.manageid = manageid == null ? null : manageid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.patriarchName
     *
     * @return the value of student.patriarchName
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public String getPatriarchname() {
        return patriarchname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.patriarchName
     *
     * @param patriarchname the value for student.patriarchName
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public void setPatriarchname(String patriarchname) {
        this.patriarchname = patriarchname == null ? null : patriarchname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studystatus
     *
     * @return the value of student.studystatus
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public String getStudystatus() {
        return studystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studystatus
     *
     * @param studystatus the value for student.studystatus
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public void setStudystatus(String studystatus) {
        this.studystatus = studystatus == null ? null : studystatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.isRelation
     *
     * @return the value of student.isRelation
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public Integer getIsrelation() {
        return isrelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.isRelation
     *
     * @param isrelation the value for student.isRelation
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public void setIsrelation(Integer isrelation) {
        this.isrelation = isrelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.patriarch
     *
     * @return the value of student.patriarch
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public String getPatriarch() {
        return patriarch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.patriarch
     *
     * @param patriarch the value for student.patriarch
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public void setPatriarch(String patriarch) {
        this.patriarch = patriarch == null ? null : patriarch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.updateTime
     *
     * @return the value of student.updateTime
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public Integer getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.updateTime
     *
     * @param updatetime the value for student.updateTime
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public void setUpdatetime(Integer updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.namePinyin
     *
     * @return the value of student.namePinyin
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public String getNamepinyin() {
        return namepinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.namePinyin
     *
     * @param namepinyin the value for student.namePinyin
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public void setNamepinyin(String namepinyin) {
        this.namepinyin = namepinyin == null ? null : namepinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.remark
     *
     * @return the value of student.remark
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.remark
     *
     * @param remark the value for student.remark
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}