package com.xuxincheng.bean;

import java.util.ArrayList;
import java.util.List;

public class StudentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public StudentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUuidIsNull() {
            addCriterion("uuid is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("uuid is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("uuid =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("uuid <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("uuid >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("uuid >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("uuid <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("uuid <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("uuid like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("uuid not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("uuid in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("uuid not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("uuid between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("uuid not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(Integer value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(Integer value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(Integer value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(Integer value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(Integer value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(Integer value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<Integer> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<Integer> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(Integer value1, Integer value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(Integer value1, Integer value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andGradeidIsNull() {
            addCriterion("gradeId is null");
            return (Criteria) this;
        }

        public Criteria andGradeidIsNotNull() {
            addCriterion("gradeId is not null");
            return (Criteria) this;
        }

        public Criteria andGradeidEqualTo(String value) {
            addCriterion("gradeId =", value, "gradeid");
            return (Criteria) this;
        }

        public Criteria andGradeidNotEqualTo(String value) {
            addCriterion("gradeId <>", value, "gradeid");
            return (Criteria) this;
        }

        public Criteria andGradeidGreaterThan(String value) {
            addCriterion("gradeId >", value, "gradeid");
            return (Criteria) this;
        }

        public Criteria andGradeidGreaterThanOrEqualTo(String value) {
            addCriterion("gradeId >=", value, "gradeid");
            return (Criteria) this;
        }

        public Criteria andGradeidLessThan(String value) {
            addCriterion("gradeId <", value, "gradeid");
            return (Criteria) this;
        }

        public Criteria andGradeidLessThanOrEqualTo(String value) {
            addCriterion("gradeId <=", value, "gradeid");
            return (Criteria) this;
        }

        public Criteria andGradeidLike(String value) {
            addCriterion("gradeId like", value, "gradeid");
            return (Criteria) this;
        }

        public Criteria andGradeidNotLike(String value) {
            addCriterion("gradeId not like", value, "gradeid");
            return (Criteria) this;
        }

        public Criteria andGradeidIn(List<String> values) {
            addCriterion("gradeId in", values, "gradeid");
            return (Criteria) this;
        }

        public Criteria andGradeidNotIn(List<String> values) {
            addCriterion("gradeId not in", values, "gradeid");
            return (Criteria) this;
        }

        public Criteria andGradeidBetween(String value1, String value2) {
            addCriterion("gradeId between", value1, value2, "gradeid");
            return (Criteria) this;
        }

        public Criteria andGradeidNotBetween(String value1, String value2) {
            addCriterion("gradeId not between", value1, value2, "gradeid");
            return (Criteria) this;
        }

        public Criteria andMeetphoneIsNull() {
            addCriterion("meetPhone is null");
            return (Criteria) this;
        }

        public Criteria andMeetphoneIsNotNull() {
            addCriterion("meetPhone is not null");
            return (Criteria) this;
        }

        public Criteria andMeetphoneEqualTo(String value) {
            addCriterion("meetPhone =", value, "meetphone");
            return (Criteria) this;
        }

        public Criteria andMeetphoneNotEqualTo(String value) {
            addCriterion("meetPhone <>", value, "meetphone");
            return (Criteria) this;
        }

        public Criteria andMeetphoneGreaterThan(String value) {
            addCriterion("meetPhone >", value, "meetphone");
            return (Criteria) this;
        }

        public Criteria andMeetphoneGreaterThanOrEqualTo(String value) {
            addCriterion("meetPhone >=", value, "meetphone");
            return (Criteria) this;
        }

        public Criteria andMeetphoneLessThan(String value) {
            addCriterion("meetPhone <", value, "meetphone");
            return (Criteria) this;
        }

        public Criteria andMeetphoneLessThanOrEqualTo(String value) {
            addCriterion("meetPhone <=", value, "meetphone");
            return (Criteria) this;
        }

        public Criteria andMeetphoneLike(String value) {
            addCriterion("meetPhone like", value, "meetphone");
            return (Criteria) this;
        }

        public Criteria andMeetphoneNotLike(String value) {
            addCriterion("meetPhone not like", value, "meetphone");
            return (Criteria) this;
        }

        public Criteria andMeetphoneIn(List<String> values) {
            addCriterion("meetPhone in", values, "meetphone");
            return (Criteria) this;
        }

        public Criteria andMeetphoneNotIn(List<String> values) {
            addCriterion("meetPhone not in", values, "meetphone");
            return (Criteria) this;
        }

        public Criteria andMeetphoneBetween(String value1, String value2) {
            addCriterion("meetPhone between", value1, value2, "meetphone");
            return (Criteria) this;
        }

        public Criteria andMeetphoneNotBetween(String value1, String value2) {
            addCriterion("meetPhone not between", value1, value2, "meetphone");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Integer value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Integer value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Integer value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Integer value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Integer value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Integer> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Integer> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Integer value1, Integer value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Integer value1, Integer value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andIstrainexpIsNull() {
            addCriterion("isTrainExp is null");
            return (Criteria) this;
        }

        public Criteria andIstrainexpIsNotNull() {
            addCriterion("isTrainExp is not null");
            return (Criteria) this;
        }

        public Criteria andIstrainexpEqualTo(Integer value) {
            addCriterion("isTrainExp =", value, "istrainexp");
            return (Criteria) this;
        }

        public Criteria andIstrainexpNotEqualTo(Integer value) {
            addCriterion("isTrainExp <>", value, "istrainexp");
            return (Criteria) this;
        }

        public Criteria andIstrainexpGreaterThan(Integer value) {
            addCriterion("isTrainExp >", value, "istrainexp");
            return (Criteria) this;
        }

        public Criteria andIstrainexpGreaterThanOrEqualTo(Integer value) {
            addCriterion("isTrainExp >=", value, "istrainexp");
            return (Criteria) this;
        }

        public Criteria andIstrainexpLessThan(Integer value) {
            addCriterion("isTrainExp <", value, "istrainexp");
            return (Criteria) this;
        }

        public Criteria andIstrainexpLessThanOrEqualTo(Integer value) {
            addCriterion("isTrainExp <=", value, "istrainexp");
            return (Criteria) this;
        }

        public Criteria andIstrainexpIn(List<Integer> values) {
            addCriterion("isTrainExp in", values, "istrainexp");
            return (Criteria) this;
        }

        public Criteria andIstrainexpNotIn(List<Integer> values) {
            addCriterion("isTrainExp not in", values, "istrainexp");
            return (Criteria) this;
        }

        public Criteria andIstrainexpBetween(Integer value1, Integer value2) {
            addCriterion("isTrainExp between", value1, value2, "istrainexp");
            return (Criteria) this;
        }

        public Criteria andIstrainexpNotBetween(Integer value1, Integer value2) {
            addCriterion("isTrainExp not between", value1, value2, "istrainexp");
            return (Criteria) this;
        }

        public Criteria andCreatoridIsNull() {
            addCriterion("creatorId is null");
            return (Criteria) this;
        }

        public Criteria andCreatoridIsNotNull() {
            addCriterion("creatorId is not null");
            return (Criteria) this;
        }

        public Criteria andCreatoridEqualTo(String value) {
            addCriterion("creatorId =", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotEqualTo(String value) {
            addCriterion("creatorId <>", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridGreaterThan(String value) {
            addCriterion("creatorId >", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridGreaterThanOrEqualTo(String value) {
            addCriterion("creatorId >=", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridLessThan(String value) {
            addCriterion("creatorId <", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridLessThanOrEqualTo(String value) {
            addCriterion("creatorId <=", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridLike(String value) {
            addCriterion("creatorId like", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotLike(String value) {
            addCriterion("creatorId not like", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridIn(List<String> values) {
            addCriterion("creatorId in", values, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotIn(List<String> values) {
            addCriterion("creatorId not in", values, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridBetween(String value1, String value2) {
            addCriterion("creatorId between", value1, value2, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotBetween(String value1, String value2) {
            addCriterion("creatorId not between", value1, value2, "creatorid");
            return (Criteria) this;
        }

        public Criteria andSerialIsNull() {
            addCriterion("serial is null");
            return (Criteria) this;
        }

        public Criteria andSerialIsNotNull() {
            addCriterion("serial is not null");
            return (Criteria) this;
        }

        public Criteria andSerialEqualTo(String value) {
            addCriterion("serial =", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialNotEqualTo(String value) {
            addCriterion("serial <>", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialGreaterThan(String value) {
            addCriterion("serial >", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialGreaterThanOrEqualTo(String value) {
            addCriterion("serial >=", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialLessThan(String value) {
            addCriterion("serial <", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialLessThanOrEqualTo(String value) {
            addCriterion("serial <=", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialLike(String value) {
            addCriterion("serial like", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialNotLike(String value) {
            addCriterion("serial not like", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialIn(List<String> values) {
            addCriterion("serial in", values, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialNotIn(List<String> values) {
            addCriterion("serial not in", values, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialBetween(String value1, String value2) {
            addCriterion("serial between", value1, value2, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialNotBetween(String value1, String value2) {
            addCriterion("serial not between", value1, value2, "serial");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andSchoolidIsNull() {
            addCriterion("schoolId is null");
            return (Criteria) this;
        }

        public Criteria andSchoolidIsNotNull() {
            addCriterion("schoolId is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolidEqualTo(String value) {
            addCriterion("schoolId =", value, "schoolid");
            return (Criteria) this;
        }

        public Criteria andSchoolidNotEqualTo(String value) {
            addCriterion("schoolId <>", value, "schoolid");
            return (Criteria) this;
        }

        public Criteria andSchoolidGreaterThan(String value) {
            addCriterion("schoolId >", value, "schoolid");
            return (Criteria) this;
        }

        public Criteria andSchoolidGreaterThanOrEqualTo(String value) {
            addCriterion("schoolId >=", value, "schoolid");
            return (Criteria) this;
        }

        public Criteria andSchoolidLessThan(String value) {
            addCriterion("schoolId <", value, "schoolid");
            return (Criteria) this;
        }

        public Criteria andSchoolidLessThanOrEqualTo(String value) {
            addCriterion("schoolId <=", value, "schoolid");
            return (Criteria) this;
        }

        public Criteria andSchoolidLike(String value) {
            addCriterion("schoolId like", value, "schoolid");
            return (Criteria) this;
        }

        public Criteria andSchoolidNotLike(String value) {
            addCriterion("schoolId not like", value, "schoolid");
            return (Criteria) this;
        }

        public Criteria andSchoolidIn(List<String> values) {
            addCriterion("schoolId in", values, "schoolid");
            return (Criteria) this;
        }

        public Criteria andSchoolidNotIn(List<String> values) {
            addCriterion("schoolId not in", values, "schoolid");
            return (Criteria) this;
        }

        public Criteria andSchoolidBetween(String value1, String value2) {
            addCriterion("schoolId between", value1, value2, "schoolid");
            return (Criteria) this;
        }

        public Criteria andSchoolidNotBetween(String value1, String value2) {
            addCriterion("schoolId not between", value1, value2, "schoolid");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("birthday is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("birthday is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayEqualTo(Integer value) {
            addCriterion("birthday =", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotEqualTo(Integer value) {
            addCriterion("birthday <>", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThan(Integer value) {
            addCriterion("birthday >", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(Integer value) {
            addCriterion("birthday >=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThan(Integer value) {
            addCriterion("birthday <", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(Integer value) {
            addCriterion("birthday <=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayIn(List<Integer> values) {
            addCriterion("birthday in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotIn(List<Integer> values) {
            addCriterion("birthday not in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayBetween(Integer value1, Integer value2) {
            addCriterion("birthday between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotBetween(Integer value1, Integer value2) {
            addCriterion("birthday not between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andEnameIsNull() {
            addCriterion("ename is null");
            return (Criteria) this;
        }

        public Criteria andEnameIsNotNull() {
            addCriterion("ename is not null");
            return (Criteria) this;
        }

        public Criteria andEnameEqualTo(String value) {
            addCriterion("ename =", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameNotEqualTo(String value) {
            addCriterion("ename <>", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameGreaterThan(String value) {
            addCriterion("ename >", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameGreaterThanOrEqualTo(String value) {
            addCriterion("ename >=", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameLessThan(String value) {
            addCriterion("ename <", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameLessThanOrEqualTo(String value) {
            addCriterion("ename <=", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameLike(String value) {
            addCriterion("ename like", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameNotLike(String value) {
            addCriterion("ename not like", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameIn(List<String> values) {
            addCriterion("ename in", values, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameNotIn(List<String> values) {
            addCriterion("ename not in", values, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameBetween(String value1, String value2) {
            addCriterion("ename between", value1, value2, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameNotBetween(String value1, String value2) {
            addCriterion("ename not between", value1, value2, "ename");
            return (Criteria) this;
        }

        public Criteria andManageidIsNull() {
            addCriterion("manageId is null");
            return (Criteria) this;
        }

        public Criteria andManageidIsNotNull() {
            addCriterion("manageId is not null");
            return (Criteria) this;
        }

        public Criteria andManageidEqualTo(String value) {
            addCriterion("manageId =", value, "manageid");
            return (Criteria) this;
        }

        public Criteria andManageidNotEqualTo(String value) {
            addCriterion("manageId <>", value, "manageid");
            return (Criteria) this;
        }

        public Criteria andManageidGreaterThan(String value) {
            addCriterion("manageId >", value, "manageid");
            return (Criteria) this;
        }

        public Criteria andManageidGreaterThanOrEqualTo(String value) {
            addCriterion("manageId >=", value, "manageid");
            return (Criteria) this;
        }

        public Criteria andManageidLessThan(String value) {
            addCriterion("manageId <", value, "manageid");
            return (Criteria) this;
        }

        public Criteria andManageidLessThanOrEqualTo(String value) {
            addCriterion("manageId <=", value, "manageid");
            return (Criteria) this;
        }

        public Criteria andManageidLike(String value) {
            addCriterion("manageId like", value, "manageid");
            return (Criteria) this;
        }

        public Criteria andManageidNotLike(String value) {
            addCriterion("manageId not like", value, "manageid");
            return (Criteria) this;
        }

        public Criteria andManageidIn(List<String> values) {
            addCriterion("manageId in", values, "manageid");
            return (Criteria) this;
        }

        public Criteria andManageidNotIn(List<String> values) {
            addCriterion("manageId not in", values, "manageid");
            return (Criteria) this;
        }

        public Criteria andManageidBetween(String value1, String value2) {
            addCriterion("manageId between", value1, value2, "manageid");
            return (Criteria) this;
        }

        public Criteria andManageidNotBetween(String value1, String value2) {
            addCriterion("manageId not between", value1, value2, "manageid");
            return (Criteria) this;
        }

        public Criteria andPatriarchnameIsNull() {
            addCriterion("patriarchName is null");
            return (Criteria) this;
        }

        public Criteria andPatriarchnameIsNotNull() {
            addCriterion("patriarchName is not null");
            return (Criteria) this;
        }

        public Criteria andPatriarchnameEqualTo(String value) {
            addCriterion("patriarchName =", value, "patriarchname");
            return (Criteria) this;
        }

        public Criteria andPatriarchnameNotEqualTo(String value) {
            addCriterion("patriarchName <>", value, "patriarchname");
            return (Criteria) this;
        }

        public Criteria andPatriarchnameGreaterThan(String value) {
            addCriterion("patriarchName >", value, "patriarchname");
            return (Criteria) this;
        }

        public Criteria andPatriarchnameGreaterThanOrEqualTo(String value) {
            addCriterion("patriarchName >=", value, "patriarchname");
            return (Criteria) this;
        }

        public Criteria andPatriarchnameLessThan(String value) {
            addCriterion("patriarchName <", value, "patriarchname");
            return (Criteria) this;
        }

        public Criteria andPatriarchnameLessThanOrEqualTo(String value) {
            addCriterion("patriarchName <=", value, "patriarchname");
            return (Criteria) this;
        }

        public Criteria andPatriarchnameLike(String value) {
            addCriterion("patriarchName like", value, "patriarchname");
            return (Criteria) this;
        }

        public Criteria andPatriarchnameNotLike(String value) {
            addCriterion("patriarchName not like", value, "patriarchname");
            return (Criteria) this;
        }

        public Criteria andPatriarchnameIn(List<String> values) {
            addCriterion("patriarchName in", values, "patriarchname");
            return (Criteria) this;
        }

        public Criteria andPatriarchnameNotIn(List<String> values) {
            addCriterion("patriarchName not in", values, "patriarchname");
            return (Criteria) this;
        }

        public Criteria andPatriarchnameBetween(String value1, String value2) {
            addCriterion("patriarchName between", value1, value2, "patriarchname");
            return (Criteria) this;
        }

        public Criteria andPatriarchnameNotBetween(String value1, String value2) {
            addCriterion("patriarchName not between", value1, value2, "patriarchname");
            return (Criteria) this;
        }

        public Criteria andStudystatusIsNull() {
            addCriterion("studystatus is null");
            return (Criteria) this;
        }

        public Criteria andStudystatusIsNotNull() {
            addCriterion("studystatus is not null");
            return (Criteria) this;
        }

        public Criteria andStudystatusEqualTo(String value) {
            addCriterion("studystatus =", value, "studystatus");
            return (Criteria) this;
        }

        public Criteria andStudystatusNotEqualTo(String value) {
            addCriterion("studystatus <>", value, "studystatus");
            return (Criteria) this;
        }

        public Criteria andStudystatusGreaterThan(String value) {
            addCriterion("studystatus >", value, "studystatus");
            return (Criteria) this;
        }

        public Criteria andStudystatusGreaterThanOrEqualTo(String value) {
            addCriterion("studystatus >=", value, "studystatus");
            return (Criteria) this;
        }

        public Criteria andStudystatusLessThan(String value) {
            addCriterion("studystatus <", value, "studystatus");
            return (Criteria) this;
        }

        public Criteria andStudystatusLessThanOrEqualTo(String value) {
            addCriterion("studystatus <=", value, "studystatus");
            return (Criteria) this;
        }

        public Criteria andStudystatusLike(String value) {
            addCriterion("studystatus like", value, "studystatus");
            return (Criteria) this;
        }

        public Criteria andStudystatusNotLike(String value) {
            addCriterion("studystatus not like", value, "studystatus");
            return (Criteria) this;
        }

        public Criteria andStudystatusIn(List<String> values) {
            addCriterion("studystatus in", values, "studystatus");
            return (Criteria) this;
        }

        public Criteria andStudystatusNotIn(List<String> values) {
            addCriterion("studystatus not in", values, "studystatus");
            return (Criteria) this;
        }

        public Criteria andStudystatusBetween(String value1, String value2) {
            addCriterion("studystatus between", value1, value2, "studystatus");
            return (Criteria) this;
        }

        public Criteria andStudystatusNotBetween(String value1, String value2) {
            addCriterion("studystatus not between", value1, value2, "studystatus");
            return (Criteria) this;
        }

        public Criteria andIsrelationIsNull() {
            addCriterion("isRelation is null");
            return (Criteria) this;
        }

        public Criteria andIsrelationIsNotNull() {
            addCriterion("isRelation is not null");
            return (Criteria) this;
        }

        public Criteria andIsrelationEqualTo(Integer value) {
            addCriterion("isRelation =", value, "isrelation");
            return (Criteria) this;
        }

        public Criteria andIsrelationNotEqualTo(Integer value) {
            addCriterion("isRelation <>", value, "isrelation");
            return (Criteria) this;
        }

        public Criteria andIsrelationGreaterThan(Integer value) {
            addCriterion("isRelation >", value, "isrelation");
            return (Criteria) this;
        }

        public Criteria andIsrelationGreaterThanOrEqualTo(Integer value) {
            addCriterion("isRelation >=", value, "isrelation");
            return (Criteria) this;
        }

        public Criteria andIsrelationLessThan(Integer value) {
            addCriterion("isRelation <", value, "isrelation");
            return (Criteria) this;
        }

        public Criteria andIsrelationLessThanOrEqualTo(Integer value) {
            addCriterion("isRelation <=", value, "isrelation");
            return (Criteria) this;
        }

        public Criteria andIsrelationIn(List<Integer> values) {
            addCriterion("isRelation in", values, "isrelation");
            return (Criteria) this;
        }

        public Criteria andIsrelationNotIn(List<Integer> values) {
            addCriterion("isRelation not in", values, "isrelation");
            return (Criteria) this;
        }

        public Criteria andIsrelationBetween(Integer value1, Integer value2) {
            addCriterion("isRelation between", value1, value2, "isrelation");
            return (Criteria) this;
        }

        public Criteria andIsrelationNotBetween(Integer value1, Integer value2) {
            addCriterion("isRelation not between", value1, value2, "isrelation");
            return (Criteria) this;
        }

        public Criteria andPatriarchIsNull() {
            addCriterion("patriarch is null");
            return (Criteria) this;
        }

        public Criteria andPatriarchIsNotNull() {
            addCriterion("patriarch is not null");
            return (Criteria) this;
        }

        public Criteria andPatriarchEqualTo(String value) {
            addCriterion("patriarch =", value, "patriarch");
            return (Criteria) this;
        }

        public Criteria andPatriarchNotEqualTo(String value) {
            addCriterion("patriarch <>", value, "patriarch");
            return (Criteria) this;
        }

        public Criteria andPatriarchGreaterThan(String value) {
            addCriterion("patriarch >", value, "patriarch");
            return (Criteria) this;
        }

        public Criteria andPatriarchGreaterThanOrEqualTo(String value) {
            addCriterion("patriarch >=", value, "patriarch");
            return (Criteria) this;
        }

        public Criteria andPatriarchLessThan(String value) {
            addCriterion("patriarch <", value, "patriarch");
            return (Criteria) this;
        }

        public Criteria andPatriarchLessThanOrEqualTo(String value) {
            addCriterion("patriarch <=", value, "patriarch");
            return (Criteria) this;
        }

        public Criteria andPatriarchLike(String value) {
            addCriterion("patriarch like", value, "patriarch");
            return (Criteria) this;
        }

        public Criteria andPatriarchNotLike(String value) {
            addCriterion("patriarch not like", value, "patriarch");
            return (Criteria) this;
        }

        public Criteria andPatriarchIn(List<String> values) {
            addCriterion("patriarch in", values, "patriarch");
            return (Criteria) this;
        }

        public Criteria andPatriarchNotIn(List<String> values) {
            addCriterion("patriarch not in", values, "patriarch");
            return (Criteria) this;
        }

        public Criteria andPatriarchBetween(String value1, String value2) {
            addCriterion("patriarch between", value1, value2, "patriarch");
            return (Criteria) this;
        }

        public Criteria andPatriarchNotBetween(String value1, String value2) {
            addCriterion("patriarch not between", value1, value2, "patriarch");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Integer value) {
            addCriterion("updateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Integer value) {
            addCriterion("updateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Integer value) {
            addCriterion("updateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("updateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Integer value) {
            addCriterion("updateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Integer value) {
            addCriterion("updateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Integer> values) {
            addCriterion("updateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Integer> values) {
            addCriterion("updateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Integer value1, Integer value2) {
            addCriterion("updateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Integer value1, Integer value2) {
            addCriterion("updateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andNamepinyinIsNull() {
            addCriterion("namePinyin is null");
            return (Criteria) this;
        }

        public Criteria andNamepinyinIsNotNull() {
            addCriterion("namePinyin is not null");
            return (Criteria) this;
        }

        public Criteria andNamepinyinEqualTo(String value) {
            addCriterion("namePinyin =", value, "namepinyin");
            return (Criteria) this;
        }

        public Criteria andNamepinyinNotEqualTo(String value) {
            addCriterion("namePinyin <>", value, "namepinyin");
            return (Criteria) this;
        }

        public Criteria andNamepinyinGreaterThan(String value) {
            addCriterion("namePinyin >", value, "namepinyin");
            return (Criteria) this;
        }

        public Criteria andNamepinyinGreaterThanOrEqualTo(String value) {
            addCriterion("namePinyin >=", value, "namepinyin");
            return (Criteria) this;
        }

        public Criteria andNamepinyinLessThan(String value) {
            addCriterion("namePinyin <", value, "namepinyin");
            return (Criteria) this;
        }

        public Criteria andNamepinyinLessThanOrEqualTo(String value) {
            addCriterion("namePinyin <=", value, "namepinyin");
            return (Criteria) this;
        }

        public Criteria andNamepinyinLike(String value) {
            addCriterion("namePinyin like", value, "namepinyin");
            return (Criteria) this;
        }

        public Criteria andNamepinyinNotLike(String value) {
            addCriterion("namePinyin not like", value, "namepinyin");
            return (Criteria) this;
        }

        public Criteria andNamepinyinIn(List<String> values) {
            addCriterion("namePinyin in", values, "namepinyin");
            return (Criteria) this;
        }

        public Criteria andNamepinyinNotIn(List<String> values) {
            addCriterion("namePinyin not in", values, "namepinyin");
            return (Criteria) this;
        }

        public Criteria andNamepinyinBetween(String value1, String value2) {
            addCriterion("namePinyin between", value1, value2, "namepinyin");
            return (Criteria) this;
        }

        public Criteria andNamepinyinNotBetween(String value1, String value2) {
            addCriterion("namePinyin not between", value1, value2, "namepinyin");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student
     *
     * @mbggenerated do_not_delete_during_merge Tue Nov 26 18:48:52 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student
     *
     * @mbggenerated Tue Nov 26 18:48:52 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}